social-sharing-app:
  images:
    profile:
      upload-path: social-sharing-app-server/images/profile
    posts:
      upload-path: social-sharing-app-server/images/posts

spring:
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
